export const FLOOR_LAYOUT = {
  main_facility: {
    server_room: {
      label: "Server Room",
      x: 4,
      y: 5,
      w: 16,
      h: 14,
    },
    meeting_room: {
      label: "Meeting Room",
      x: 20,
      y: 5,
      w: 22,
      h: 14,
    },
    multi_purpose_room: {
      label: "Multi-purpose Room",
      x: 42,
      y: 5,
      w: 22,
      h: 14,
    },

    male_toilet: {
      label: "Male Toilet",
      x: 82,
      y: 5,
      w: 8,
      h: 10,
      markerDisabled: true,
      compact: true,
    },
    female_toilet: {
      label: "Female Toilet",
      x: 82,
      y: 15,
      w: 8,
      h: 10,
      markerDisabled: true,
      compact: true,
    },
    stair: {
      label: "Stair",
      x: 82,
      y: 25,
      w: 8,
      h: 14,
      markerDisabled: true,
      compact: true,
    },
    elevator: {
      label: "Elevator",
      x: 82,
      y: 39,
      w: 8,
      h: 10,
      markerDisabled: true,
      compact: true,
    },

    gathering_area: {
      label: "Gathering Area",
      x: 16,
      y: 25,
      w: 44,
      h: 22,
      variant: "soft",
    },

    conference_room: {
      label: "Conference Room",
      x: 4,
      y: 62,
      w: 24,
      h: 22,
    },
    canteen: {
      label: "Canteen",
      x: 28,
      y: 62,
      w: 24,
      h: 22,
    },
    lobby: {
      label: "Lobby",
      x: 52,
      y: 62,
      w: 28,
      h: 22,
    },
  },

  office_floor: {
    ceo_office: {
      label: "CEO Office",
      x: 4,
      y: 5,
      w: 18,
      h: 14,
    },
    manager_office: {
      label: "Manager Office",
      x: 22,
      y: 5,
      w: 22,
      h: 14,
    },
    executive_office: {
      label: "Executive Office",
      x: 44,
      y: 5,
      w: 24,
      h: 14,
    },

    male_toilet: {
      label: "Male Toilet",
      x: 82,
      y: 5,
      w: 8,
      h: 10,
      markerDisabled: true,
      compact: true,
    },
    female_toilet: {
      label: "Female Toilet",
      x: 82,
      y: 15,
      w: 8,
      h: 10,
      markerDisabled: true,
      compact: true,
    },
    stair: {
      label: "Stair",
      x: 82,
      y: 25,
      w: 8,
      h: 14,
      markerDisabled: true,
      compact: true,
    },
    elevator: {
      label: "Elevator",
      x: 82,
      y: 39,
      w: 8,
      h: 10,
      markerDisabled: true,
      compact: true,
    },

    office_area: {
      label: "Office Area",
      x: 4,
      y: 19,
      w: 64,
      h: 60,
    },
    command_center: {
      label: "Command Center",
      x: 72,
      y: 58,
      w: 18,
      h: 20,
    },
  },

  basement: {
    parking_area: {
      label: "Parking Area",
      x: 4,
      y: 8,
      w: 74,
      h: 76,
    },
    store_room: {
      label: "Store Room",
      x: 82,
      y: 8,
      w: 10,
      h: 16,
      compact: true,
    },
    stair: {
      label: "Stair",
      x: 82,
      y: 28,
      w: 10,
      h: 14,
      markerDisabled: true,
      compact: true,
    },
    elevator: {
      label: "Elevator",
      x: 82,
      y: 42,
      w: 10,
      h: 10,
      markerDisabled: true,
      compact: true,
    },
  },
};